name: Update latest
on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync code and packaging from upstreams
        run: |
          set -euxo pipefail

          # 添加上游仓库
          git remote add openatom https://github.com/OpenAtom-Linyaps/linyaps
          git fetch openatom --no-tags

          git remote add deepin https://github.com/deepin-community/linyaps
          git fetch deepin --no-tags

          # 以 openatom/master 作为基线
          git reset --hard openatom/master

          # 仅同步 deepin 的 1.10 分支里的打包目录
          git checkout deepin/release/1.10 -- debian
          
          # 创建并添加 debian/watch 文件，指示 uscan 自动从 GitHub 下载源包
          echo "version=4" > debian/watch
          echo "https://github.com/OpenAtom-Linyaps/linyaps/archive/refs/heads/master.zip" >> debian/watch

          # 移除任何来自上游的 CI 配置，避免循环触发
          rm -rf .github || true

      - name: Commit as obs_latest (with deepin patches)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: obs_latest
          create_branch: true
          push_options: --force
          commit_message: "Automated Change (sync OpenAtom base + deepin/1.10 packaging)"

      - name: Make nopatch variant
        run: |
          set -euxo pipefail

          # 删除 deepin 的 patches（nopatch 变体）
          rm -rf debian/patches || true

          # 删除 preloader 相关条目（文件可能不存在，失败不终止）
          sed -i '/preloader/d' debian/linglong-bin.postinst || true
          sed -i '/preloader/d' debian/linglong-bin.install || true

          # 关闭单元测试（若 CMakeLists.txt 不同也不报错）
          sed -i '/set(ENABLE_TESTING/{n; s/ON/OFF/}' CMakeLists.txt || true

      - name: Commit as obs_latest_nopatch (without deepin patches)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: obs_latest_nopatch
          create_branch: true
          push_options: --force
          commit_message: "Automated Change (nopatch variant for non-deepin builds)"
      
      - name: Run uscan to download tarball
        run: |
          set -euxo pipefail

          # 安装 uscan 工具，下载源包
          sudo apt-get update
          sudo apt-get install -y devscripts

          # 使用 uscan 自动下载源包并重命名为 .orig.tar.gz
          uscan --download-current-version --rename --destdir ../sources
